### ISSUE TITLE
check from address

### ISSUE THREAD

**Issue by vcordes79** [extremeshok/spamassassin-from_is_not_reply-to#10]
Hi,

thanks for the plugins, great work. Is it possible to check the from address? I get a lot of Spam with From addresses like:

`From: "auto-confirm@amazon.com" <mary@doublediamonddairy.com>`

So basically I would like to check if display name is an email address and compare it to the from address.

Thanks,
Volker

**Comment by spec1re** [comment]
You looking for a Plugin, which is build in SA version 3.4.2

https://spamassassin.apache.org/full/3.4.x/doc/Mail_SpamAssassin_Plugin_FromNameSpoof.txt

or just add this custom SA rule:

```
header	  FROM_NAME_SPOOF From =~ /^.*@.*<.*@.*>/i
describe  FROM_NAME_SPOOF FromNameSpoof
score 	  FROM_NAME_SPOOF 5.0
```
Gruß Spec
