### ISSUE TITLE
Use more securiteinfo signatures

### ISSUE THREAD

**Issue by dominicraf** [extremeshok/spamassassin-from_is_not_reply-to#11]
Can the script be adapted to also update/use the following securiteinfo files:
spam_marketing.ndb
securiteinfoascii.hdb
securiteinfoandroid.hdb
securiteinfopdf.hdb
?

**Comment by extremeshok** [comment]
Sure, do you have the False/positive ratings for them ?

Feel free to do a PR on the dev branch for the master.conf
