### ISSUE TITLE
error on debian jessie.

### ISSUE THREAD

**Issue by thctlo** [extremeshok/spamassassin-from_is_not_reply-to#2]
Hai, 

Just tried you our fromreplyto, but it errors.. 

Jun 29 13:01:05 core spamd[321]: rules: failed to run FROM_IS_REPLY_TO test, skipping:
Jun 29 13:01:05 core spamd[321]:  (Can't locate object method "check_for_from_is_reply_to" via package "Mail: [...]:SpamAssassin::PerMsgStatus" at (eval 1982) line 1059.
Jun 29 13:01:05 core spamd[321]: )

spamassassin -V
SpamAssassin version 3.4.0
  running on Perl version 5.20.2

tested this also on a debian wheezy with spamassassin 3.4 on it from backports, same error.

**Comment by extremeshok** [comment]
Run the following

```
spamassassin -D --lint 2>&1 | grep -i failed
```

We use it in production on multiple debian jessie servers.

**Comment by extremeshok** [comment]
The **plugins** dir needs to be in the same location as the **01_extremeshok_fromreplyto.cf** file

**Comment by thctlo** [comment]
output of spamassassin -D --lint 2>&1 | grep -i failed

Jul  8 11:42:27.292 [7592] dbg: diag: [...] module not installed: Digest::SHA1 ('require' failed)
Jul  8 11:42:29.664 [7592] dbg: config: warning: no description set for KAM_RPTR_FAILED
Jul  8 11:42:30.631 [7592] dbg: rules: CBJ_GiveMeABreak merged duplicates: KAM_IFRAME KAM_RAPTOR KAM_RPTR_FAILED KAM_RPTR_PASSED KAM_RPTR_SUSPECT
Jul  8 11:42:31.698 [7592] warn: rules: failed to run FROM_IS_REPLY_TO test, skipping:

**Comment by thctlo** [comment]
als tried spamassassin from bpo 

spamassassin -V
SpamAssassin version 3.4.1
  running on Perl version 5.20.2
root@core:/etc/spamassassin# spamassassin -D --lint 2>&1 | grep -i failed
Jul  8 11:56:44.585 [10225] dbg: diag: [...] module not installed: Digest::SHA1 ('require' failed)
Jul  8 11:56:45.720 [10225] dbg: config: warning: no description set for KAM_RPTR_FAILED
Jul  8 11:56:46.425 [10225] dbg: rules: CBJ_GiveMeABreak merged duplicates: KAM_IFRAME KAM_RAPTOR KAM_RPTR_FAILED KAM_RPTR_PASSED KAM_RPTR_SUSPECT
Jul  8 11:56:46.750 [10225] warn: rules: failed to run FROM_IS_REPLY_TO test, skipping:

**Comment by thctlo** [comment]
the exact message is : 
Jul  8 11:59:24.589 [10324] warn: rules: failed to run FROM_IS_REPLY_TO test, skipping:
Jul  8 11:59:24.589 [10324] warn:  (Can't locate object method "check_for_from_is_reply_to" via package "Mail: [...]:SpamAssassin::PerMsgStatus" at (eval 1790) line 1083.
Jul  8 11:59:24.589 [10324] warn: )

**Comment by thctlo** [comment]
ok, i installed libdigest-sha1-perl from the packetfence repo, only perl thing that was missing. 

Jul  8 12:04:30.347 [11809] dbg: config: fixed relative path: /etc/spamassassin/plugins/FromIsNotReplyTo.pm
Jul  8 12:04:30.348 [11809] dbg: plugin: loading FromIsNotReplyTo from /etc/spamassassin/plugins/FromIsNotReplyTo.pm
Jul  8 12:04:30.349 [11809] dbg: config: fixed relative path: /etc/spamassassin/plugins/FromAndReplyToIsNotSameDomain.pm
Jul  8 12:04:30.349 [11809] dbg: plugin: loading FromAndReplyToIsNotSameDomain from /etc/spamassassin/plugins/FromAndReplyToIsNotSameDomain.pm
Jul  8 12:04:30.350 [11809] dbg: config: fixed relative path: /etc/spamassassin/plugins/FromIsTo.pm
Jul  8 12:04:30.350 [11809] dbg: plugin: loading FromIsTo from /etc/spamassassin/plugins/FromIsTo.pm
Jul  8 12:04:30.350 [11809] dbg: config: fixed relative path: /etc/spamassassin/plugins/FromIsNotReplyToWhitelist.pm
Jul  8 12:04:30.351 [11809] dbg: plugin: loading FromIsNotReplyToWhitelist from /etc/spamassassin/plugins/FromIsNotReplyToWhitelist.pm
Jul  8 12:04:30.351 [11809] dbg: config: fixed relative path: /etc/spamassassin/plugins/FromIsReplyTo.pm
Jul  8 12:04:30.352 [11809] dbg: plugin: did not register FromIsTo, already registered

and spamassassin -D --lint 2>&1 | grep -i failed reports : 
Jul  8 12:07:02.272 [11831] warn: rules: failed to run FROM_IS_REPLY_TO test, skipping:

**Comment by thctlo** [comment]
and as last. that is all i could find. in the mail log when recieving messages. 

Jul  8 12:53:01 core spamd[11790]:  (Can't locate object method "check_for_from_is_reply_to" via package "Mail: [...]:SpamAssassin::PerMsgStatus" at (eval 1744) line 2333, <GEN98> line 120.

some perl package missing maybe ?

**Comment by extremeshok** [comment]
Ive done some changes to the class initialization and plugin requirements.

Please check with the latest version.

**Comment by thctlo** [comment]
Hai, Its perfect now, thank you for this great plugin.

**Comment by thctlo** [comment]
i forgot to mention. 
Works perfect now on debian Jessie. and on debian Wheezy. 
Tested both. ( spamassassin minimal 3.4.x on both servers )

**Comment by extremeshok** [comment]
Pleasure, thanks for reporting
