### ISSUE TITLE
FromIsTo Plugin confusing Scoring

### ISSUE THREAD

**Issue by derhelge** [extremeshok/spamassassin-from_is_not_reply-to#3]
In `01_extremeshok_fromreplyto.cf` it says:

```
## Score 6 points to mail when from and to are the same.
loadplugin FromIsTo plugins/FromIsTo.pm
header FROM_IS_TO eval:check_for_from_is_to()
score FROM_IS_TO -0.5
```

So the score is actually -0.5 - but the comment says 6 points (to Slytherin). If this is just to test the plugin, it would be nice to add some descriptive text.

Cheers :-)

**Comment by extremeshok** [comment]
Fixed in e11384faff4acc3f23c81f3c220b6ace31f2993c
