### ISSUE TITLE
Not Working - Array Index values wrong

### ISSUE THREAD

**Issue by slider182** [extremeshok/spamassassin-from_is_not_reply-to#5]
the index values of this code (eg. line 51, 55, and so on) are wrong - the conditions are one value to high.

line 51: if (( $#check_fromParts ge 2) && ( $#check_fromParts ge 2 ))

should be: if (( $#check_fromParts ge 1) && ( $#check_fromParts ge 1 ))

example: test@test.com

check_fromParts[0]=test
check_fromParts[1]=com

$#check_fromParts = 1 in this case

$# = count of elements within array - 1

**Comment by extremeshok** [comment]
fixed with commit c95beda7d510fcfa8561a79d6f585a4dd16f511c
