### ISSUE TITLE
failed to parse plugin /etc/spamassassin/plugins/FromAndToIsSameDomain.pm

### ISSUE THREAD

**Issue by ricariel** [extremeshok/spamassassin-from_is_not_reply-to#7]
Hi

My testing installation shows up the following error. My System is Debian stable up to date. Do you need further information?

Greetings Fabrice

plugin: failed to parse plugin /etc/spamassassin/plugins/FromAndToIsSameDomain.pm: syntax error at /etc/spamassassin/plugins/FromAndToIsSameDomain.pm line 30, near "check_to
  my "
Compilation failed in require at /usr/share/perl5/Mail/SpamAssassin/PluginHandler.pm line 109.

**Comment by ricariel** [comment]
#8

**Comment by fkoyer** [comment]
I am getting this error as well. The pull request from @schindlerf  fixes it. Can this be merged into the repository?

**Comment by extremeshok** [comment]
merged
