### ISSUE TITLE
Contact forms

### ISSUE THREAD

**Issue by Ninos** [extremeshok/spamassassin-from_is_not_reply-to#9]
Hey there,
with your rules I have problems using contact forms (on websites). The problem here is following:
In the from-field normally you're using noreply@domain.tld, in the Reply-To-field the senders email (variable). Because Reply-To and From are not the same (email, domain, ..) I get a high spam score. Can your filter may be disabled for internal mails (if From is an internal domain)?

**Comment by extremeshok** [comment]
Added whitelisting with 5d5dd2c  

View the comment in  spamassassin-extremeshok_fromreplyto/plugins/FromIsNotReplyToWhitelist.pm

**Comment by Ninos** [comment]
Wow, fast reply, thank you! But seems I cannot use it for shared hosting. Is there a function in spamassassin I can get all local domains on that server?
